// SPDX-FileCopyrightText: 2026 The ucs-exporter authors
//
// SPDX-License-Identifier: GPL-3.0-only

package main

import (
	"fmt"
	"io"
	"strings"
	"text/tabwriter"

	"github.com/damienstuart/ucs-exporter/internal/config"
	"github.com/damienstuart/ucs-exporter/internal/module"
	"github.com/damienstuart/ucs-exporter/internal/modules"
)

func runCheck(w io.Writer, configFile string) error {
	cfg, err := loadConfig(configFile, nil)
	if err != nil {
		return err
	}
	for _, warning := range cfg.Warnings() {
		fmt.Fprintln(w, "warning:", warning)
	}
	tw := tabwriter.NewWriter(w, 0, 4, 2, ' ', 0)
	fmt.Fprintln(tw, "DOMAIN\tADDRESS\tUSER\tINTERVAL\tTLS VERIFY\tMODULES")
	for _, r := range cfg.ResolvedDomains() {
		mods := "all"
		if r.Modules != nil {
			mods = strings.Join(r.Modules, ",")
		}
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\t%v\t%s\n", r.Name, r.Address, r.Username, r.Interval, !r.TLS.InsecureSkipVerify, mods)
	}
	if err := tw.Flush(); err != nil {
		return err
	}
	if u := cfg.UnlistedDomains; u.Enabled {
		fmt.Fprintf(w, "unlisted domains enabled: allow %q, max %d\n", u.Allow, u.MaxDomains)
	}
	fmt.Fprintf(w, "%s: OK\n", configFile)
	return nil
}

func runModules(w io.Writer, markdown bool) error {
	mods := modules.Builtin(config.Options{VirtualVLANs: "full", IOMHostPorts: true, AdaptorUplinkErrors: true, FirmwareTypes: config.DefaultFirmwareTypes})
	if !markdown {
		tw := tabwriter.NewWriter(w, 0, 4, 2, ' ', 0)
		fmt.Fprintln(tw, "MODULE\tMETRICS\tCLASSES\tDESCRIPTION")
		for _, m := range mods {
			fmt.Fprintf(tw, "%s\t%d\t%d\t%s\n", m.Name(), len(module.Metrics(m)), len(m.Queries()), m.Description())
		}
		return tw.Flush()
	}
	fmt.Fprintln(w, "<!-- Generated by `ucs-exporter modules --markdown`; do not edit. -->")
	for _, m := range mods {
		fmt.Fprintf(w, "\n### `%s`\n\n%s\n\n", m.Name(), m.Description())
		fmt.Fprintln(w, "| Metric | Type | Labels | Description |")
		fmt.Fprintln(w, "|---|---|---|---|")
		for _, info := range module.Metrics(m) {
			labels := append([]string{"domain"}, info.Labels...)
			fmt.Fprintf(w, "| `%s` | %s | %s | %s |\n", info.Name, info.Type, "`"+strings.Join(labels, "`, `")+"`",
				strings.ReplaceAll(info.Help, "|", `\|`))
		}
	}
	return nil
}
